"""Modify columns to users table

Revision ID: 27a7fee1a3e6
Revises: 584c64d9b21d
Create Date: 2025-10-21 13:18:11.744173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '27a7fee1a3e6'
down_revision: Union[str, None] = '584c64d9b21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('air_conditioners', sa.Column('maintainer_id', sa.Integer(), nullable=True))
    op.alter_column('air_conditioners', 'make_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('air_conditioners', 'capacity_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('air_conditioners', 'refrigerant_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'air_conditioners', 'maintainers', ['maintainer_id'], ['id'])
    op.alter_column('capacities', 'tonnage',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               type_=sa.DECIMAL(precision=4, scale=1),
               existing_nullable=False)
    op.alter_column('maintainers', 'subdivision_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('maintenance_dates', sa.Column('ac_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'maintenance_dates', 'air_conditioners', ['ac_id'], ['id'])
    op.alter_column('maintenance_records', 'maintenance_type',
               existing_type=mysql.ENUM('Monthly', 'Quarterly', 'SixMonthly', 'Yearly', 'Unscheduled'),
               type_=sa.Enum('Monthly', 'Quarterly', 'SixMonthly', 'Yearly', 'Unscheduled', name='maint_type_enum', native_enum=False),
               existing_nullable=True)
    op.alter_column('subdivisions', 'division_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('users', sa.Column('subdivision_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'designation',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_foreign_key(None, 'users', 'subdivisions', ['subdivision_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'designation',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('users', 'subdivision_id')
    op.alter_column('subdivisions', 'division_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('maintenance_records', 'maintenance_type',
               existing_type=sa.Enum('Monthly', 'Quarterly', 'SixMonthly', 'Yearly', 'Unscheduled', name='maint_type_enum', native_enum=False),
               type_=mysql.ENUM('Monthly', 'Quarterly', 'SixMonthly', 'Yearly', 'Unscheduled'),
               existing_nullable=True)
    op.drop_constraint(None, 'maintenance_dates', type_='foreignkey')
    op.drop_column('maintenance_dates', 'ac_id')
    op.alter_column('maintainers', 'subdivision_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('capacities', 'tonnage',
               existing_type=sa.DECIMAL(precision=4, scale=1),
               type_=mysql.DECIMAL(precision=2, scale=1),
               existing_nullable=False)
    op.drop_constraint(None, 'air_conditioners', type_='foreignkey')
    op.alter_column('air_conditioners', 'refrigerant_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('air_conditioners', 'capacity_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('air_conditioners', 'make_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('air_conditioners', 'maintainer_id')
    # ### end Alembic commands ###
