"""Add new columns to existing table

Revision ID: 584c64d9b21d
Revises: 0c90aa487f63
Create Date: 2025-10-21 11:58:11.340924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '584c64d9b21d'
down_revision: Union[str, None] = '0c90aa487f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('air_conditioners', sa.Column('precise_location', sa.Text(), nullable=False))
    op.drop_constraint('air_conditioners_ibfk_2', 'air_conditioners', type_='foreignkey')
    op.drop_constraint('air_conditioners_ibfk_3', 'air_conditioners', type_='foreignkey')
    op.drop_column('air_conditioners', 'maintainer_id')
    op.drop_column('air_conditioners', 'maintenance_dates_id')
    op.add_column('users', sa.Column('is_maintainer', sa.Boolean(), nullable=False))
    op.drop_index('email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint('users_ibfk_2', 'users', type_='foreignkey')
    op.drop_column('users', 'subdivision_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subdivision_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('users_ibfk_2', 'users', 'subdivisions', ['subdivision_id'], ['id'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('email', 'users', ['email'], unique=False)
    op.drop_column('users', 'is_maintainer')
    op.add_column('air_conditioners', sa.Column('maintenance_dates_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('air_conditioners', sa.Column('maintainer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('air_conditioners_ibfk_3', 'air_conditioners', 'maintenance_dates', ['maintenance_dates_id'], ['id'])
    op.create_foreign_key('air_conditioners_ibfk_2', 'air_conditioners', 'maintainers', ['maintainer_id'], ['id'])
    op.drop_column('air_conditioners', 'precise_location')
    # ### end Alembic commands ###
