"""Some changes done

Revision ID: c81e06e39998
Revises: 27a7fee1a3e6
Create Date: 2025-10-23 13:47:35.088929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c81e06e39998'
down_revision: Union[str, None] = '27a7fee1a3e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('air_conditioners', sa.Column('model', sa.String(length=255), nullable=False))
    op.add_column('air_conditioners', sa.Column('install_date', sa.Date(), nullable=False))
    op.add_column('air_conditioners', sa.Column('manufacturing_date', sa.Date(), nullable=False))
    op.add_column('air_conditioners', sa.Column('division_id', sa.Integer(), nullable=True))
    op.alter_column('air_conditioners', 'serial_number',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_foreign_key(None, 'air_conditioners', 'makes', ['make_id'], ['id'])
    op.create_foreign_key(None, 'air_conditioners', 'capacities', ['capacity_id'], ['id'])
    op.create_foreign_key(None, 'air_conditioners', 'refrigerants', ['refrigerant_id'], ['id'])
    op.create_foreign_key(None, 'air_conditioners', 'subdivisions', ['subdivision_id'], ['id'])
    op.create_foreign_key(None, 'air_conditioners', 'divisions', ['division_id'], ['id'])
    op.create_foreign_key(None, 'air_conditioners', 'maintainers', ['maintainer_id'], ['id'])
    op.alter_column('checklist_items', 'description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('checklist_items', 'maintenance_type',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.create_foreign_key(None, 'maintainers', 'subdivisions', ['subdivision_id'], ['id'])
    op.create_foreign_key(None, 'maintainers', 'users', ['user_id'], ['id'])
    op.alter_column('maintenance_checklist_records', 'maintenance_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('maintenance_checklist_records', 'checklist_item_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('maintenance_checklist_records', 'done',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_foreign_key(None, 'maintenance_checklist_records', 'checklist_items', ['checklist_item_id'], ['id'])
    op.create_foreign_key(None, 'maintenance_checklist_records', 'maintenance_records', ['maintenance_id'], ['id'])
    op.create_foreign_key(None, 'maintenance_dates', 'air_conditioners', ['ac_id'], ['id'])
    op.alter_column('maintenance_records', 'ac_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('maintenance_records', 'maintainer_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('maintenance_records', 'maintenance_type',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.alter_column('maintenance_records', 'maintenance_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('maintenance_records', 'status',
               existing_type=mysql.VARCHAR(length=9),
               nullable=False)
    op.alter_column('maintenance_records', 'is_completed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_foreign_key(None, 'maintenance_records', 'air_conditioners', ['ac_id'], ['id'])
    op.create_foreign_key(None, 'maintenance_records', 'maintainers', ['maintainer_id'], ['id'])
    op.alter_column('makes', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=70),
               existing_nullable=False)
    op.alter_column('parts_replaced', 'maintenance_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('parts_replaced', 'part_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('parts_replaced', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'parts_replaced', 'maintenance_records', ['maintenance_id'], ['id'])
    op.create_foreign_key(None, 'subdivisions', 'divisions', ['division_id'], ['id'])
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'designation',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.create_foreign_key(None, 'users', 'subdivisions', ['subdivision_id'], ['id'])
    op.create_foreign_key(None, 'users', 'divisions', ['division_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('users', 'designation',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'subdivisions', type_='foreignkey')
    op.drop_constraint(None, 'parts_replaced', type_='foreignkey')
    op.alter_column('parts_replaced', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('parts_replaced', 'part_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('parts_replaced', 'maintenance_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('makes', 'name',
               existing_type=sa.String(length=70),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'maintenance_records', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_records', type_='foreignkey')
    op.alter_column('maintenance_records', 'is_completed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('maintenance_records', 'status',
               existing_type=mysql.VARCHAR(length=9),
               nullable=True)
    op.alter_column('maintenance_records', 'maintenance_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('maintenance_records', 'maintenance_type',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.alter_column('maintenance_records', 'maintainer_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('maintenance_records', 'ac_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'maintenance_dates', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_checklist_records', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_checklist_records', type_='foreignkey')
    op.alter_column('maintenance_checklist_records', 'done',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('maintenance_checklist_records', 'checklist_item_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('maintenance_checklist_records', 'maintenance_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'maintainers', type_='foreignkey')
    op.drop_constraint(None, 'maintainers', type_='foreignkey')
    op.alter_column('checklist_items', 'maintenance_type',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.alter_column('checklist_items', 'description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.drop_constraint(None, 'air_conditioners', type_='foreignkey')
    op.drop_constraint(None, 'air_conditioners', type_='foreignkey')
    op.drop_constraint(None, 'air_conditioners', type_='foreignkey')
    op.drop_constraint(None, 'air_conditioners', type_='foreignkey')
    op.drop_constraint(None, 'air_conditioners', type_='foreignkey')
    op.drop_constraint(None, 'air_conditioners', type_='foreignkey')
    op.alter_column('air_conditioners', 'serial_number',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('air_conditioners', 'division_id')
    op.drop_column('air_conditioners', 'manufacturing_date')
    op.drop_column('air_conditioners', 'install_date')
    op.drop_column('air_conditioners', 'model')
    # ### end Alembic commands ###
